# Generated by Django 2.0.5 on 2018-05-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=64)),
                ('api_token', models.CharField(max_length=128)),
            ],
        ),
    ]
